{% set name = "mmf_setup" %}
{% set version = "0.1.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .
  #hg_rev: {{ version }}
  #hg_url: https://hg@bitbucket.org/mforbes/mmf_setup

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - setuptools
    - nbstripout >=0.2.0
  run:
    - python
    - nbstripout >=0.2.0
    - python-hglib

test:
  source_files:
    - '*'
    - '.*'
  imports:
    - mmf_setup
    - mmf_setup.set_path
  requires:
    - coverage
    - notebook
    - pytest >=2.8.1
    - pytest-cov >=2.2.0
    - pytest-flake8
  commands:
    - make test

about:
  home: https://bitbucket.org/mforbes/mmf_setup
  license: GNU General Public v3 or later (GPLv3+)
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Python Tools
  doc_url:
  dev_url:
